name: Go
on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:
jobs:
  update:
    name: Update Index
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go run -v ./main
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ALGOLIA_APP: ${{ secrets.ALGOLIA_APP }}
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
